Solved task pick
js-tasks-ru/js-20200622_mihail-letov pull request #1
Opened 2020-06-26 11:01 UTC by mletov

Solved task pick

2020-06-26 11:08 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-06-26 11:45 UTC, jsru commented
@dosandk ping :)

2020-06-26 13:48 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	var newObj = {};
про `var` мы еще не говорили, но в при современной разработке `var` не используется - применяйте либо `let` либо `const` для объявления переменных

2020-06-26 13:49 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +	var resObj = {};
`var` - необходимо заменить на `let` или `const`

2020-06-26 14:04 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let index in fields) {
в данном случае применение итерации через `for ...in` не имеет смысла. Лучше использовать встроенный метод массивов `forEach` для итерации

2020-06-26 14:05 UTC, dosandk requested changes
Глянь пожалуйста на комменты

2020-06-26 14:13 UTC, mletov commented
Спасибо за фидбэк, конечно, все поправлю.
Во только у меня пул реквесты не отправляются

2020-06-26 18:35 UTC, jsru commented
@dosandk ping :)

2020-06-27 07:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return a new sorted array
- should return sorted by "asc" array of strings
- should return sorted by "desc" array of strings
- should correctly sort language-specific characters
- should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
Первая задача
+ should return sum of numbers
```

2020-06-27 17:06 UTC, mletov commented
@dosandk ping :)
Владимир, я закомитил все тесты прошли

2020-06-27 17:10 UTC, jsru commented
@dosandk ping :)

2020-06-27 18:07 UTC, jsru commented
@dosandk ping :)

2020-06-27 18:19 UTC, jsru commented
@dosandk ping :)

2020-06-27 19:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +//https://thread.engineering/2018-08-29-searching-and-sorting-text-with-diacritical-marks-in-javascript/
хорошая статья, только технику из статьи нужно было применить в случае если бы задача была про "search" или "filter"
В нашем случае нужно строки сортировать, поэтому заменять диакритические символы не было необходимости

2020-06-27 19:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let arRes = arr.slice().sort(compareFunction);
более короткий и современный способ скопировать массив
```
const copy = [...arr];
```

2020-06-27 19:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	if (param === 'desc') arRes = arRes.reverse();
было бы неплохо избавиться от операции `arRes.reverse()` и уже на этапе сортировки знать каким образом необходимо ее осуществить

2020-06-27 19:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let aWithoutDiacritics = a.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
попробуйте решить задачу через `localeCompare`

2020-06-27 19:19 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	let newObj = {};
`newObj` должен быть объявлена через `const`

2020-06-27 19:19 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +	let resObj = {};
`resObj` должна быть объявлена через `const`

2020-06-27 19:19 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +	let keys = Object.keys(obj);
снова `const`

2020-06-27 19:20 UTC, dosandk requested changes
решения принимаются, необходимо исправить только задачу "sortStrings"

2020-06-28 06:53 UTC, mletov commented
Владимир, обновил

2020-06-28 06:55 UTC, jsru commented
@dosandk ping :)

2020-06-28 11:56 UTC, jsru commented
@dosandk ping :)

2020-06-28 12:17 UTC, dosandk approved these changes
задачи приняты

2020-06-28 12:17 UTC, merged