04-oop-basic-intro-to-dom
js-tasks-ru/js-20200622_mihail-letov pull request #3
Opened 2020-07-06 17:25 UTC by mletov

2020-07-06 17:31 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-06 18:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be update by new values
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-06 18:56 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.html
> +      //document.getElementById("dashboard__charts").append(ordersChart.element);
не оставляйте пожалуйста закоментированный код - это плохая привычка/практика
Ваши коллеги будут ломать голову почему это было закоментированн: баг ли это, случайность, быстрый фикс???

2020-07-06 18:57 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return !(this.options && this.options.data && this.options.data.length > 0);
для того чтобы не было вот таких сложных проверок, следует использовать параметры по умолчанию в `constructor`

2020-07-06 18:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return !(this.options && this.options.data && this.options.data.length > 0);
про параметры по умолчанию можно почитать здесь https://github.com/dosandk/js-20200622/tree/master/additional

2020-07-06 19:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.options.data = newOptions.bodyData ?? [];
оператор `??` используют в случаях когда нужно использовать все falsy значения кроме `null` и `undefined`
В данном методе компонент не будет в восторге если `newOptions.bodyData` будет задано как `NaN` так как именно `NaN` будет присвоен в `this.options.data` благодаря оператору `??`

2020-07-06 19:02 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return 50;
В данном случае getter не нужен, getter - это в большинстве случаев обертка вокруг другого значения класса, например на занятии мы разбирали доступ к `this.name` через геттер `this.firstName`, а значение 50 - это просто значение, а не свойство класса

2020-07-06 19:04 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        const container = document.createElement("div");
старайтесь организовать добавление элементов внутри `innerHTM` вот так:

```javascript
element.innerHTML = `
  <div class="foo">
     <div>Header</div>
     <div>${this.getBody()}</div>
  </div>
```

2020-07-06 19:05 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +       if (this.options && this.options.label)  title.innerHTML = this.options.label;
не экономьте на фигурных скобках в if

2020-07-06 19:06 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    get element()
нет необходимости в данном getter и setter.
Попробуйте ответить на вопрос: "Зачем они здесь использованы?"

2020-07-06 19:06 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let chart = this._element.querySelector(".column-chart__chart");
`chart` - это `const`

2020-07-06 19:08 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(options) {
было бы неплохо добавить значения по умолчанию 
код станет гораздо чище

про параметры по умолчанию можно почитать тут https://github.com/dosandk/js-20200622/tree/master/additional

2020-07-06 19:11 UTC, dosandk requested changes
Необходимо:
1. Почистить код - удалить все закоментированные куски. Если кусок кода все же есть необходимость закоментировать и оставить в PR - дописать над "TODO: причина коментария кода"
2. Посмотреть материал по дефолтным параметрам функции - внести изменения
3. Понять зачем были использованы getter и setter - ответить на мои комментираии
4. Везде где можно собрать тимплейты через `innerHTML` - сделать это

2020-07-07 12:51 UTC, jsru commented
@dosandk ping :)

2020-07-08 09:50 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(options = {}) {
я бы советовал все таки использовать дефолтные значения в аргументах, тогда не прийдется делать вот такие проверки:
```
this.options.data = options.data || [];
```

2020-07-08 09:51 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let chart = this.element.querySelector(".column-chart__chart");
`char` длжна быть `const`

2020-07-08 09:52 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        if (this.options.data.length > 0) this.fillChartData(chart);
обычно такие проверки сокращают вот так:
```
if (this.options.data.length)
```
на скобках в `if` тоже не принято экономить

2020-07-08 09:54 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +
было бы неплохо использовать деструкцию, чтобы не обращаться каждый раз к `this.options`
```
const { link, label, value } = this.options;
```

2020-07-08 09:55 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        if (this.options.data.length === 0) wrapper.classList.add("column-chart_loading");
обычно такие проверки сокращают:

```
if (!this.options.data.length) {

}
```

2020-07-08 09:55 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +	    if (this.options.link) {
логику создания `link` - можно вынести в отдельный метод

2020-07-08 09:56 UTC, dosandk approved these changes
решение принимается, посмотрите пожалуйста комментарии :mag:

2020-07-08 09:56 UTC, merged